#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-float
Version  : 0.3.2
Release  : 19
URL      : https://cran.r-project.org/src/contrib/float_0.3-2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/float_0.3-2.tar.gz
Summary  : 32-Bit Floats
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause
Requires: R-float-lib = %{version}-%{release}
Requires: R-float-license = %{version}-%{release}
BuildRequires : buildreq-R

%description
(double precision) vectors/matrices. However, sometimes single precision (or
    less!) is more than enough for a particular task.  This package extends R's
    linear algebra facilities to include 32-bit float (single precision) data.
    Float vectors/matrices have half the precision of their "numeric"-type
    counterparts but are generally faster to numerically operate on, for a
    performance vs accuracy trade-off.  The internal representation is an S4
    class, which allows us to keep the syntax identical to that of base R's.
    Interaction between floats and base types for binary operators is generally
    possible; in these cases, type promotion always defaults to the higher
    precision.  The package ships with copies of the single precision 'BLAS' and
    'LAPACK', which are automatically built in the event they are not available
    on the system.

%package lib
Summary: lib components for the R-float package.
Group: Libraries
Requires: R-float-license = %{version}-%{release}

%description lib
lib components for the R-float package.


%package license
Summary: license components for the R-float package.
Group: Default

%description license
license components for the R-float package.


%prep
%setup -q -n float
pushd ..
cp -a float buildavx2
popd
pushd ..
cp -a float buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737144289

%install
export SOURCE_DATE_EPOCH=1737144289
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-float
cp %{_builddir}/float/src/lapack/LICENSE %{buildroot}/usr/share/package-licenses/R-float/a8513998d02e2b32909109fb55411ea61e6c3428 || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/float/CITATION
/usr/lib64/R/library/float/DESCRIPTION
/usr/lib64/R/library/float/INDEX
/usr/lib64/R/library/float/LICENSE
/usr/lib64/R/library/float/Meta/Rd.rds
/usr/lib64/R/library/float/Meta/data.rds
/usr/lib64/R/library/float/Meta/features.rds
/usr/lib64/R/library/float/Meta/hsearch.rds
/usr/lib64/R/library/float/Meta/links.rds
/usr/lib64/R/library/float/Meta/nsInfo.rds
/usr/lib64/R/library/float/Meta/package.rds
/usr/lib64/R/library/float/Meta/vignette.rds
/usr/lib64/R/library/float/NAMESPACE
/usr/lib64/R/library/float/R/float
/usr/lib64/R/library/float/R/float.rdb
/usr/lib64/R/library/float/R/float.rdx
/usr/lib64/R/library/float/benchmarks/cov.r
/usr/lib64/R/library/float/benchmarks/lmfit.r
/usr/lib64/R/library/float/benchmarks/prcomp.r
/usr/lib64/R/library/float/data/Rdata.rdb
/usr/lib64/R/library/float/data/Rdata.rds
/usr/lib64/R/library/float/data/Rdata.rdx
/usr/lib64/R/library/float/doc/float.Rnw
/usr/lib64/R/library/float/doc/float.pdf
/usr/lib64/R/library/float/doc/index.html
/usr/lib64/R/library/float/help/AnIndex
/usr/lib64/R/library/float/help/aliases.rds
/usr/lib64/R/library/float/help/float.rdb
/usr/lib64/R/library/float/help/float.rdx
/usr/lib64/R/library/float/help/paths.rds
/usr/lib64/R/library/float/html/00Index.html
/usr/lib64/R/library/float/html/R.css
/usr/lib64/R/library/float/include/float/float32.h
/usr/lib64/R/library/float/include/float/slapack.h
/usr/lib64/R/library/float/libs/libfloat.a
/usr/lib64/R/library/float/tests/arithmetic.r
/usr/lib64/R/library/float/tests/backsolve.r
/usr/lib64/R/library/float/tests/bind.r
/usr/lib64/R/library/float/tests/c.r
/usr/lib64/R/library/float/tests/chol.r
/usr/lib64/R/library/float/tests/chol2inv.r
/usr/lib64/R/library/float/tests/colSums.r
/usr/lib64/R/library/float/tests/comparison.r
/usr/lib64/R/library/float/tests/cond.r
/usr/lib64/R/library/float/tests/crossprod.r
/usr/lib64/R/library/float/tests/diag.r
/usr/lib64/R/library/float/tests/eigen.r
/usr/lib64/R/library/float/tests/extremes.r
/usr/lib64/R/library/float/tests/isSymmetric.r
/usr/lib64/R/library/float/tests/math.r
/usr/lib64/R/library/float/tests/matmult.r
/usr/lib64/R/library/float/tests/na.r
/usr/lib64/R/library/float/tests/norm.r
/usr/lib64/R/library/float/tests/print.r
/usr/lib64/R/library/float/tests/qr.r
/usr/lib64/R/library/float/tests/rand.r
/usr/lib64/R/library/float/tests/rep.r
/usr/lib64/R/library/float/tests/scale.r
/usr/lib64/R/library/float/tests/sign.r
/usr/lib64/R/library/float/tests/solve.r
/usr/lib64/R/library/float/tests/sum.r
/usr/lib64/R/library/float/tests/svd.r
/usr/lib64/R/library/float/tests/sweep.r
/usr/lib64/R/library/float/tests/xpose.r

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/float/libs/float.so
/V4/usr/lib64/R/library/float/libs/float.so
/usr/lib64/R/library/float/libs/float.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-float/a8513998d02e2b32909109fb55411ea61e6c3428
